# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
      - main
      - vr/integration-tests
  pull_request:
    branches:
      - main
      - vr/integration-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Install dependencies
        run: go mod download

      - name: Install ginkgo
        run: |
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          ginkgo version

      # - name: Build API Server
      #   run: go build -v ./cmd/api/main.go

      # - name: Build Worker
      #   run: go build -v ./cmd/worker/main.go

      # - name: Run unit tests
      #   run: ginkgo -v pkg/validation

      - name: Create .env.test file
        run: cp .env.test.example .env.test

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.35.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Start docker compose
        run: docker-compose --env-file .env.test -f docker-compose.yml -f docker-compose.test.yml up -d

      - name: Run integration tests
        run: ginkgo -v tests/integration
